color molokai

syntax on
set number
set relativenumber
set laststatus=2

set tabstop=8
set autoindent
set smartindent
set expandtab
set shiftwidth=4
set softtabstop=4

set guioptions-=m
set guioptions-=T

set hidden

set ignorecase
set title

execute pathogen#infect()
call pathogen#helptags()

